# This file was generated by GoReleaser. DO NOT EDIT.
class Kratos < Formula
  desc ""
  homepage "https://www.ory.sh"
  version "0.0.1-alpha.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ory/kratos/releases/download/v0.0.1-alpha.7/kratos_0.0.1-alpha.7_macos_amd64.tar.gz"
    sha256 "68050b60f7dfa70651ad0ef2773914109045a7750a79ac5463fbf2f82080f890"
  elsif OS.linux?
  end

  def install
    bin.install "kratos-sqlite"
    bin.install "kratos"
  end
end
